-- Drop tables if they exist
DROP TABLE IF EXISTS cocktail_local;
DROP TABLE IF EXISTS cocktail_person;
DROP TABLE IF EXISTS ingredient_cocktail;
DROP TABLE IF EXISTS cocktail;
DROP TABLE IF EXISTS glas;
DROP TABLE IF EXISTS ingredient;
DROP TABLE IF EXISTS local;
DROP TABLE IF EXISTS person;

-- Create tables
CREATE TABLE glas (
	GID SERIAL PRIMARY KEY,
	GNAME VARCHAR(255)
);

CREATE TABLE cocktail (
	CID SERIAL PRIMARY KEY,
	CNAME VARCHAR(255),
	ALKOHOLISCH CHAR(1),
	GID INT,
	FOREIGN KEY (GID) REFERENCES glas(GID)
);

CREATE TABLE ingredient (
	ZID SERIAL PRIMARY KEY,
	ZNAME VARCHAR(255),
	ALKOHOLGEHALT DECIMAL(5,2)
);

CREATE TABLE local (
	LID SERIAL PRIMARY KEY,
	LNAME VARCHAR(255),
	PLZ INT,
	STADT VARCHAR(255)
);

CREATE TABLE person (
	PID SERIAL PRIMARY KEY,
	NAME VARCHAR(255),
	GEBURTSDATUM DATE
);

CREATE TABLE cocktail_local (
	CID INT,
	LID INT,
	FOREIGN KEY (CID) REFERENCES cocktail(CID),
	FOREIGN KEY (LID) REFERENCES local(LID)
);

CREATE TABLE cocktail_person(
	CID INT,
	PID1 INT,
	PID2 INT,
	FOREIGN KEY (CID) REFERENCES cocktail(CID),
	FOREIGN KEY (PID1) REFERENCES person(PID),
	FOREIGN KEY (PID2) REFERENCES person(PID)
);

CREATE TABLE ingredient_cocktail (
	ZID INT,
	CID INT,
	MENGE INT,
	FOREIGN KEY (ZID) REFERENCES ingredient(ZID),
	FOREIGN KEY (CID) REFERENCES cocktail(CID)
);